# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: productos.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'productos.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproductos.proto\x12\tproductos\"\x0f\n\rProductoVacio\"\x18\n\nProductoId\x12\n\n\x02id\x18\x01 \x01(\x05\"\x83\x01\n\x08Producto\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x0e\n\x06imagen\x18\x03 \x01(\t\x12\x0e\n\x06precio\x18\x04 \x01(\x01\x12\r\n\x05stock\x18\x05 \x01(\x05\x12\x13\n\x0bsucursal_id\x18\x06 \x01(\x05\x12\x17\n\x0fnombre_sucursal\x18\x07 \x01(\t\"8\n\x0eListaProductos\x12&\n\tproductos\x18\x01 \x03(\x0b\x32\x13.productos.Producto\"4\n\x12ResultadoOperacion\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t2\xa3\x01\n\x0fProductoService\x12\x46\n\x0fListarProductos\x12\x18.productos.ProductoVacio\x1a\x19.productos.ListaProductos\x12H\n\x10\x45liminarProducto\x12\x15.productos.ProductoId\x1a\x1d.productos.ResultadoOperacionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'productos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCTOVACIO']._serialized_start=30
  _globals['_PRODUCTOVACIO']._serialized_end=45
  _globals['_PRODUCTOID']._serialized_start=47
  _globals['_PRODUCTOID']._serialized_end=71
  _globals['_PRODUCTO']._serialized_start=74
  _globals['_PRODUCTO']._serialized_end=205
  _globals['_LISTAPRODUCTOS']._serialized_start=207
  _globals['_LISTAPRODUCTOS']._serialized_end=263
  _globals['_RESULTADOOPERACION']._serialized_start=265
  _globals['_RESULTADOOPERACION']._serialized_end=317
  _globals['_PRODUCTOSERVICE']._serialized_start=320
  _globals['_PRODUCTOSERVICE']._serialized_end=483
# @@protoc_insertion_point(module_scope)
