# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import productos_pb2 as productos__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in productos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProductoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListarProductos = channel.unary_unary(
                '/productos.ProductoService/ListarProductos',
                request_serializer=productos__pb2.ProductoVacio.SerializeToString,
                response_deserializer=productos__pb2.ListaProductos.FromString,
                _registered_method=True)
        self.EliminarProducto = channel.unary_unary(
                '/productos.ProductoService/EliminarProducto',
                request_serializer=productos__pb2.ProductoId.SerializeToString,
                response_deserializer=productos__pb2.ResultadoOperacion.FromString,
                _registered_method=True)


class ProductoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListarProductos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EliminarProducto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListarProductos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarProductos,
                    request_deserializer=productos__pb2.ProductoVacio.FromString,
                    response_serializer=productos__pb2.ListaProductos.SerializeToString,
            ),
            'EliminarProducto': grpc.unary_unary_rpc_method_handler(
                    servicer.EliminarProducto,
                    request_deserializer=productos__pb2.ProductoId.FromString,
                    response_serializer=productos__pb2.ResultadoOperacion.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'productos.ProductoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('productos.ProductoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListarProductos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/productos.ProductoService/ListarProductos',
            productos__pb2.ProductoVacio.SerializeToString,
            productos__pb2.ListaProductos.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EliminarProducto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/productos.ProductoService/EliminarProducto',
            productos__pb2.ProductoId.SerializeToString,
            productos__pb2.ResultadoOperacion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
